### ISSUE TITLE
Counter page generate a new call of Auth0 login 

### ISSUE THREAD

**Issue by jprimke-AXAP** [CrahunGit/Auth0BlazorWebAppSample#3]
Hello 

If I open the Counter page I receive a lot of not expected data:

![image](https://github.com/CrahunGit/Auth0BlazorWebAppSample/assets/88764005/b03296f4-09d7-4713-a74c-8330edff5230)

It seems that the API call open a new login on Auth0. 

If you call https://localhost:7078/hello directly the error does not occur.

Could you check this please.

**Comment by CrahunGit** [comment]
If I navigate with the navmenu to counter page it redirects me to the auth0's login page. Can you provide more details about how do you enter to the counter page?

**Comment by jprimke-AXAP** [comment]
I have logged in before then I go to Counter page. 

I comment out the call SayHello in OnInitialize and the same issue occurs if I press the button "SayHello".

It is possible to see your configuration on Auth0 because I believe If it runs correctly on your side it can be a misconfiguration on my side.

**Comment by jprimke-AXAP** [comment]
I believe here is an problem with call the server API from client side.

**Comment by CrahunGit** [comment]
It's pretty simple, just like this

![imagen](https://github.com/CrahunGit/Auth0BlazorWebAppSample/assets/12015993/38b7af1a-c501-4fdb-850f-8e7991698dc0)

An oidc application. All on server side. Client side has nothing to configure since it trusts the cookie server adds.

**Comment by jprimke-AXAP** [comment]
In your code you do not use Audience and Secret. Is it necessary?

**Comment by jprimke-AXAP** [comment]
In addition: Thank you for this sample and your support.

**Comment by jprimke-AXAP** [comment]
I am not sure what Audience means.

**Comment by CrahunGit** [comment]
You're right,. Yo don't need them. Maybe the error is line 32, 

```chasrp
.AddHttpClient("API", client => client.BaseAddress = new Uri("https://localhost:7078/"))
```

This is the api (aka server) url.

**Comment by jprimke-AXAP** [comment]
Yes, i did not change your launch settings.

**Comment by CrahunGit** [comment]
> I am not sure what Audience means.

Audience is your front (client) url.

**Comment by jprimke-AXAP** [comment]
Did you make more than standard configuration on the application page on Auth0 site?

**Comment by CrahunGit** [comment]
Yes, allow post redircects, nothing elese

**Comment by jprimke** [comment]
It works if the component runs as WebAssembly.

**Comment by jprimke** [comment]
Do you see a possibility it solve the issue with the InteractiveServer?

**Comment by CrahunGit** [comment]
Yes. I think so. But now it does a http call. I’ll need to modify it a little bit.

**Comment by CrahunGit** [comment]
Here you go. Now it has mediatr inside all projects. Onehandler for server without httpclient and another with httpclient for client side.
